// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR_NFhwB71PXvcr1f4ELaZFJO8qTRCmW8',
    appId: '1:32119811033:web:449c7b97e9eaa0053447c8',
    messagingSenderId: '32119811033',
    projectId: 'test-9f415',
    authDomain: 'test-9f415.firebaseapp.com',
    storageBucket: 'test-9f415.appspot.com',
    measurementId: 'G-2FE2SHEY0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA89UjY-N6Xpta_c-0QVCrHEoW8atjQpAQ',
    appId: '1:32119811033:android:e8c68ea72bda0c883447c8',
    messagingSenderId: '32119811033',
    projectId: 'test-9f415',
    storageBucket: 'test-9f415.appspot.com',
  );
}
